### ISSUE TITLE
Cut a new release (via git tag)?

### ISSUE THREAD

**Issue by solderjs** [mstorsjo/fdk-aac#109]
Looks like there has been a _ton_ of work since v2.0.0, but it's not represented in any of the releases.

It would be _awesome_ if there were some tags for tracking stability.

I'm not sure if all the commits represent so many patches, or actual new features, but perhaps it's great enough volume of commits to consider bumping to `v2.1.0`?

```
git tag v2.1.0
git push --tags
```

**Comment by mstorsjo** [comment]
There's literally zero new features since v2.0.0 in this repo, only bug fixes for issues founds by fuzzers. (The upstream merge flow from AOSP makes some things show up as many individual commits with even more merge commits inbetween though.) As it still represents potential real issues I guess I could make a v2.0.1 out of it.

Upstream in AOSP there seems to have been some new changes as well, but mostly minor changes, with potentially better fixes for fuzzer issues than the ones I've made.

I guess I could release v2.0.1 with what I have right now, then merge AOSP master and see if I could get rid of some of my own fuzzer fixes and let that stabilize for some time.

**Comment by mstorsjo** [comment]
Now there's a v2.0.1 tag out there, with the current master contents. Will try to proceed to merge latest AOSP master on top after that.
