### ISSUE TITLE
compile in centos 7, using ndk14c ,find error

### ISSUE THREAD

**Issue by mAndroidNovice** [mstorsjo/fdk-aac#111]
/tmp/ccKUhGO3.s:30: rdhi, rdlo and rm must all be different
  CXX      libSBRdec/src/psbitdec.lo
  CXX      libSBRdec/src/psdec.lo
/tmp/ccOAalDE.s: Assembler messages:
/tmp/ccOAalDE.s:30: rdhi, rdlo and rm must all be different
  CXX      libSBRdec/src/psdec_drm.lo
libSBRdec/src/lpp_tran.cpp:122:21: fatal error: log/log.h: No such file or directory
 #include "log/log.h"
                     ^
compilation terminated.
  CXX      libSBRdec/src/psdecrom_drm.lo
make: *** [libSBRdec/src/lpp_tran.lo] 错误 1
make: *** 正在等待未完成的任务....
/tmp/ccN8RLfv.s: Assembler messages:
/tmp/ccN8RLfv.s:30: rdhi, rdlo and rm must all be different
  CXX      libSBRdec/src/lpp_tran.lo
libSBRdec/src/lpp_tran.cpp:122:21: fatal error: log/log.h: No such file or directory
 #include "log/log.h"
                     ^
compilation terminated.
make: *** [libSBRdec/src/lpp_tran.lo] error 1

I can't understand what's mean and how to resolve it.
I google it and can't find the method how  to resolve it.
please help me!

**Comment by mstorsjo** [comment]
Building this project for Andoid actually isn't really supported, for a few reasons:
- fdk-aac already is available as a system component (accessible via the MediaCodec APIs) on Android since Android 4.1
- The license of fdk-aac is problematic with respect to redistribution

The error about "rdhi, rdlo and rm must all be different" probably is due to you trying to build for ARMv5, while the project's arm assembly code probably only supports ARMv7.

The second error about log/log.h being missing is because when fdk-aac is built as a part of Android, they have a few sets of android-specific logging in a few places in that file (within `#ifdef __ANDROID__`), that only works when built as part of the platform, not when built with the NDK. You can manually just remove all of these ifdefs from the file if you want to try to fix the build that way.
