### ISSUE TITLE
Unify the shared library version and package version?

### ISSUE THREAD

**Issue by bp0** [mstorsjo/fdk-aac#21]
There are many version numbers out there when it comes to FDK. Here is a list I've tried to maintain: http://wiki.hydrogenaud.io/index.php?title=Fraunhofer_FDK_AAC#Software_Versions

I was wondering if you would consider unifying the shared library version with your package version to reduce the population of version numbers by one.

Now that the so version is 1.0.0, the binary package 0.1.4 in debian will be libfdk_aac1, and libfdk_aac0 will remain based on 0.1.3 for whatever might be depending on it. The idea would be to make the next package version match the so version at 1.0.0, to maybe reduce confusion a little.

**Comment by bp0** [comment]
So it is more complicated than I imagined. That is not a surprise. :) 

I think you have indicated that you have some direct contact with the folks at Fraunhofer, but I'd imagine they don't share very many plans or give you notice of when there will be an API breaking change. It also appears that this is a static library in Android?, so maybe this kind of thing is not important to them. I'd imagine these circumstances make it hard to keep the API stable for long enough to have sensibly-numbered releases.

Maybe you are right to just keep on the way you have been. Although, it seems like there should be some indication regarding the break. The so version does still change, so there is that.

Just out of curiosity, what kind of thing might cause you to change the first or second numbers in your version scheme?

**Comment by mstorsjo** [comment]
I occasionally talk to them, yes, but they can't share much about future plans. In this case they told me not to release the new code drop right away since the calling code in libavcodec would need changes as well (and they told me a few days before the code drop). Yes, in Android this is statically linked so any API change can be dealt with in sync (although they don't seem to change the interface too recklessly so far - it could have been much worse).

I'll at least add comments in the changelog (and release announcement) pointing out that users of the decoder will need to be careful since they may need to adjust calling code in some cases.

I just found out that the decoder in the new version also adds a bit more delay of the output samples than the previous version - I'll try to look at that at as well to see if there's a way to get around it.

Instinctively to me, a change in the earlier version numbers would mean a version with significant functional changes, not just some minor API adjustments (even though adjustments that break old code is bad).

**Comment by bp0** [comment]
Alright. 

Re: New delay: https://github.com/mstorsjo/fdk-aac/commit/603f48ab99ce76f552f4f6f85d06b8c5b94c698e#diff-0972dbdca2e14fe3d67ba040f5cbdb36R175
That comment mentions some delay added with that new limiter that is now enabled by default.  

AAC_PCM_LIMITER_ENABLE can be set to 0 to turn it off. I think the AAC_DECODER_INSTANCE struct has a new extGainDelay in it that maybe tells you how much delay was added?

**Comment by mstorsjo** [comment]
Oh, thanks for pointing that out.

For finding the actual delay, CStreamInfo has got a field outputDelay now which does provide the exact delay, but being able to turn it off would be even more useful.

**Comment by bp0** [comment]
Right on.

My original question is answered. Thanks.
