### ISSUE TITLE
Access Huffman encoded and decoded data

### ISSUE THREAD

**Issue by akshaymalhotra190** [mstorsjo/fdk-aac#31]
Hi,

I want to access the spectral data before and after Huffman encoding/decoding in the encoder and in the decoder. 
For accessing spectral data before Huffman encoding,  I am using pSpectralCoefficient pointer and dumping 1024 samples (on the decoder side) and using  qcOutChannel[ch]->quantSpec and dumping 1024 samples (on the encoder side). Is this correct?

Secondly, how do access the Huffman encoded signal in the encoder and decoder. If someone can tell me the location in the code and the name of the pointer to use and the length of this data, I will be extremely thankful.

Thanks in adavnce.

Regards,
Akshay

**Comment by mstorsjo** [comment]
Please understand that this project is only about repackaging the code written by Fraunhofer, for use outside of Android. I did not write this code, and I have only read a small fraction of it (mostly while hunting for some bugs).

I don't know the answer to your question, in order to answer them I would have to sit down and read the code myself, just as you are doing.
