### ISSUE TITLE
AAC frame size in frequency domain

### ISSUE THREAD

**Issue by akshaymalhotra190** [mstorsjo/fdk-aac#32]
Hi All,

I wanted to know that what is the frame size in frequency domain?
I am dumping 1024 samples of *pSpectralCoefficient. Is that correct?
Is it possible that some frames are 1024 in length and others are a set 0f 8 frames with 128 frequency bins. If it is possible, then is there any flag that can give me this information ?

Request you to please answer my queries (this one and the previous one: https://github.com/mstorsjo/fdk-aac/issues/31).

Thank you for your time.

Regards,
Akshay Malhotra

**Comment by mstorsjo** [comment]
Please understand that this project is only about repackaging the code written by Fraunhofer, for use outside of Android. I did not write this code, and I have only read a small fraction of it (mostly while hunting for some bugs).

I don't know the answer to your question, in order to answer them I would have to sit down and read the code myself, just as you are doing.

In general, yes, for AAC, frames can either be one long frame of 1024 samples, or 8 short windows of 128 samples. But how and where this is expressed in the fdk-aac codebase, I don't know.
