### ISSUE TITLE
rdhi, rdlo and rm must all be different

### ISSUE THREAD

**Issue by joerg-krause** [mstorsjo/fdk-aac#38]
Building fdk-aac for an ARMv5te target outputs a lot of the following assembler message:

```sh
rdhi, rdlo and rm must all be different
```

I am using gcc toolchain 5.3.0 from Buildroot.

**Comment by mstorsjo** [comment]
Hi,

This warning is mostly a non-issue, but slightly annoying. This warning comes from some inline arm assembly. Basically, the inline arm assembly assumes something which is strictly not guaranteed for ARMv5TE. In practice, it is not an issue though, for at least a few reasons:

- The ARMv5 manual says:

> Specifying the same register for either \<RdHi\> and \<Rm\>, or \<RdLo\> and \<Rm\>, was previously described as producing UNPREDICTABLE results. There is no restriction in ARMv6, and it is believed all relevant ARMv4 and ARMv5 implementations do not require this restriction either, because high performance multipliers read all their operands prior to writing back any results.

Therefore in practice this is not an issue at all on ARMv6 and newer, and it should be fine in practice on ARMv5 as well.

- I'm not aware of any actual Android devices shipping with ARMv5 processors. Even if the baseline for Android on ARM is ARMv5TE, in practice even the earliest devices that shipped ran ARMv6. (The reason for using ARMv5TE as baseline might have been that the emulator only supported ARMv5 back when the decision was made.) And since Android 4.0, Android has not officially supported ARM below ARMv7 anyway. (There still have been third party ROMs for ARMv6 for some such versions.)

**Comment by joerg-krause** [comment]
I see, many thanks for clarification!

**Comment by jroseff** [comment]
This is still an issue with ARMv7 (well, ARMv7l) devices as of 2.0.3. Notably I'm not running Android, but [asus-merlin](https://www.asuswrt-merlin.net/) and [Entware](https://www.entware.net) — the host device is a fairly old ASUS RT-AC88U. /proc/cpuinfo shows this:

/tmp/fdk-aac-2.0.3# cat /proc/cpuinfo
Processor       : ARMv7 Processor rev 0 (v7l)
processor       :  0
BogoMIPS        : 2798.38
processor       : 1
BogoMIPS        : 2798.38
Features        : swp half thumb fastmult edsp 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0
Hardware        : Northstar Prototype
Revision        : 0000
Serial          : [0000000000000000](tel:0000000000000000)

or in other words, it's pretty medicore (of course). The build fails eventually with

  CXX      libSYS/src/genericStds.lo
  CXX      libSYS/src/syslib_channelMapDescr.lo
  GEN      libfdk-aac.la
 ar: libAACdec/src/FDK_delay.o: No such file or directory
make: *** [Makefile:1514: libfdk-aac.la]

but not before spamming the "rdhi, rdlo and rm must all be different" message what appears to be hundreds of times (I can re-run the build and log make to a file, then grep -c it for an exact count if requested). I actually didn't expect the build to succeed, since its on-device toolchain isn't complete and a pile of hacks, but if that message definitely isn't an actual problem then one apparently exists elsewhere: there is a libAACdec/src/FDK_delay.**lo**, but (as make says) no libAACdec/src/FDK_delay.o. The same goes for every *.cpp file in the folder, in fact.
