### ISSUE TITLE
Can't compile 0.1.5 version in Android NDK platform

### ISSUE THREAD

**Issue by mandagod** [mstorsjo/fdk-aac#54]
Can't compile 0.1.5 version in Android NDK platform.
But replace the Android.mk with the 0.1.4 version's, it will be ok.
Some issue from Android.mk.
@mstorsjo

**Comment by mstorsjo** [comment]
Building using the bundled Android.mk file is not supported, so this is not something that I'm going to fix.

To elaborate; fdk-aac is taken from the AOSP source tree, which also uses Android.mk for building. The Android.mk files used in the NDK is similar (but simplified) compared to in the full AOSP. In general, Android.mk files from AOSP need a bit of cleanup to work properly in the NDK.

Now, the fdk-aac project that you are reporting the bug to, mainly concerns itself about adding an autoconf/automake build system to the source code; we don't modify the Android.mk file that just happens to be included from AOSP.

To fix the actual issue for yourself, remove the `"-Wno-\#warnings"` part from `LOCAL_CFLAGS` in Android.mk.

If you are building the code using the NDK, you are probably thinking of redistributing the code in an android app. Keep in mind that the fdk-aac source code has a very strict, custom license - in practice you can probably not redistribute binaries legally - at least I would never do it.

If you want to use fdk-aac on Android, the same codec is already available on Android since Android 4.1; you can access it for both encoding and decoding via the MediaCodec API, so you don't need to redistribute any codec at all.

**Comment by mandagod** [comment]
@mstorsjo Thanks a lot.
