### ISSUE TITLE
Compile under Android NDK r16.1.4479499 got linker failed

### ISSUE THREAD

**Issue by timonlio** [mstorsjo/fdk-aac#81]
Compile stop by linker failed 

jni/fdk-aac-0.1.5/libAACenc/src/adj_thr.cpp
Warning:(961, 108) warning: shifting a negative signed value is undefined [-Wshift-negative-value]
Warning:(961, 108) warning: shifting a negative signed value is undefined [-Wshift-negative-value]

**Comment by mstorsjo** [comment]
The messages you quoted are warnings, not errors. You need to provide much more details about what command you ran, in what environment (a standalone toolchain built from the NDK, or manually adding the NDK paths to the PATH), etc.

**Comment by timonlio** [comment]
Just use Android Studio externalNativeBuild to compile with fdk-aac-0.1.5 internal Android.mk

**Comment by mstorsjo** [comment]
You can't build this using the Android.mk that is bundled - that's not intended or supported.

This project is about repackaging it for building outside of Android, using other build systems. The Android.mk file that is present is for when it is built as part of the full Android source tree for building a device image and is only kept around because I haven't made an effort to remove it. In the latest git version it doesn't exist any longer (since AOSP itself has changed to use a different file format for the build files) - the Android.mk that was present wasn't ever intended to be built with the NDK. (The AOSP and the NDK both used Android.mk with similar syntax, but one can't expect files from one to work in the other without changes.)

To build this with the NDK, you need to do a configure/make based build with the NDK tools (e.g. from make-standalone-toolchain.sh)

If you intend to build this for an Android app and redistribute it, keep in mind that the license of the code might be problematic for you.

And finally this code is already present on more or less all android devices since Android 4.1 - you can access it via the MediaCodec API.
