### ISSUE TITLE
Issue with decoding HE-AAC 5.1 (6 channels) RAW format

### ISSUE THREAD

**Issue by CoreTechie** [mstorsjo/fdk-aac#86]
I have this HE-AAC (v1) encoded Raw format bit-stream. This does not play with the **m4a-dec** example decoder. Decoding stops after two frames and then crashes somewhere inside the decoder library.

Bit-stream file attached:

[SAMPLE1_AACV1_64K_RAW_CH5.1.M4A.zip](https://github.com/mstorsjo/fdk-aac/files/2163585/SAMPLE1_AACV1_64K_RAW_CH5.1.M4A.zip)

**Comment by mstorsjo** [comment]
That's strange; I can decode it just fine with the current `m4a-dec` from the `decoder-example` branch.

I pushed two minor fixes for this decoder example to the branch though, you might want to recheck with those.

**Comment by CoreTechie** [comment]
Yes, those two bug fixes seems to have fixed the issue.  I am able to decode the file now. Thanks !

**Comment by mstorsjo** [comment]
Ok, great! Even without the fixes, the decoder shouldn't crash though. What exact version of libavformat/ffmpeg do you use, in case I would be able to reproduce it? I have a feeling that your suggested change to tpdec_lib.cpp actually could have a chance of fixing that crash as well...

**Comment by CoreTechie** [comment]
I am using the latest ffmpeg release build version 4.0 from this link https://ffmpeg.zeranoe.com/builds/  for linking with my environment.

Out of the two fixes you made today, the one that increases the decoded buffer **output_size** to 32KB works. This is probably necessary for channels greater than 2 (6 channels in this case). Earlier while testing 5.1 Audio in ADTS, I had to increase this size in order to fix a similar issue. In fact, I feel the output_size should depend on the number of channels & frame size. What do you say ?

My suggested changes to **tpdec_lib.cpp** is not a fix for this particular issue. But that change works for the latm bit-streams though.

**Comment by mstorsjo** [comment]
Ok, with that new version of ffmpeg, the keep side data flag isn't necessary any longer.

If you didn't have the fix from f4da0776b469f1fa6b2a753cb1824, then a too small output buffer could cause crashes.

The ouput buffer size already takes the number of channels into account, kind of. Currently it's 8 (the max number of channels the library supports decoding) times 2 (the size of a 16 bit sample) times 2048 (the largest frame size). I had missed that HE-AAC has got larger frames than other profiles, where 1024 otherwise was the largest possible frame.

**Comment by CoreTechie** [comment]
Ok, Got it. I have also introduced your fix [f4da077 ](https://github.com/mstorsjo/fdk-aac/commit/f4da0776b469f1fa6b2a753cb1824a91f05fb757) as well. The application works fine. Thanks !
