### ISSUE TITLE
Decoding a stream in Firefox Quantum

### ISSUE THREAD

**Issue by dhannyz** [mstorsjo/fdk-aac#92]
Hi there, i'm using a fdk-aac stream, coming out of a streaming software called liquidsoap
Recently i've had problems with playback in firefox, and raised an issue here
https://github.com/savonet/liquidsoap/issues/587
which relates to the following 
https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1448762

> I understand your concerns, however those files are technically invalid. Rejecting them is the right thing to do.

This leaves me in a bit of an annoying situation... Is this something you are aware of or have any plans of addressing?

**Comment by mstorsjo** [comment]
If I understand the issue correctly, the issue is about how the mp4 file is structured, not about the encoded AAC content itself. As fdk-aac does not support writing mp4 files, only encoding the AAC content itself, this doesn't relate to fdk-aac at all. What library did the writing of the mp4 container format in this case? It's either an issue with that library, or with the code calling that library (feeding it with invalid input).

**Comment by dhannyz** [comment]
@mstorsjo understood, also, it seems to be working fine now, despite earlier issues. I shall close this
